--自定义结构要大写才帅

local SA = {}

-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protobuf_pb')


SA.CLOGIN = protobuf.Descriptor();
SA.CLOGIN_USERNAME_FIELD = protobuf.FieldDescriptor();
SA.CLOGIN_PASSWORD_FIELD = protobuf.FieldDescriptor();
SA.SUSERDATA = protobuf.Descriptor();
SA.SUSERDATA_CODE_FIELD = protobuf.FieldDescriptor();
SA.SERROR = protobuf.Descriptor();
SA.SERROR_CODE_FIELD = protobuf.FieldDescriptor();
SA.SSINGLEUPDATE = protobuf.Descriptor();
SA.SSINGLEUPDATE_USERID_FIELD = protobuf.FieldDescriptor();
SA.SSINGLEUPDATE_KEYS_FIELD = protobuf.FieldDescriptor();
SA.SSINGLEUPDATE_IDS_FIELD = protobuf.FieldDescriptor();
SA.SSINGLEUPDATE_COUNTS_FIELD = protobuf.FieldDescriptor();
SA.CTEST = protobuf.Descriptor();
SA.CTEST_ID_FIELD = protobuf.FieldDescriptor();
SA.CTEST_MSG_FIELD = protobuf.FieldDescriptor();
SA.STEST = protobuf.Descriptor();
SA.STEST_ID_FIELD = protobuf.FieldDescriptor();
SA.STEST_MSG_FIELD = protobuf.FieldDescriptor();
SA.CHEART = protobuf.Descriptor();
SA.CHEART_TIME_FIELD = protobuf.FieldDescriptor();

SA.CLOGIN_USERNAME_FIELD.name = "userName"
SA.CLOGIN_USERNAME_FIELD.full_name = ".org.jiira.protobuf.CLogin.userName"
SA.CLOGIN_USERNAME_FIELD.number = 1
SA.CLOGIN_USERNAME_FIELD.index = 0
SA.CLOGIN_USERNAME_FIELD.label = 2
SA.CLOGIN_USERNAME_FIELD.has_default_value = false
SA.CLOGIN_USERNAME_FIELD.default_value = ""
SA.CLOGIN_USERNAME_FIELD.type = 9
SA.CLOGIN_USERNAME_FIELD.cpp_type = 9

SA.CLOGIN_PASSWORD_FIELD.name = "passWord"
SA.CLOGIN_PASSWORD_FIELD.full_name = ".org.jiira.protobuf.CLogin.passWord"
SA.CLOGIN_PASSWORD_FIELD.number = 2
SA.CLOGIN_PASSWORD_FIELD.index = 1
SA.CLOGIN_PASSWORD_FIELD.label = 2
SA.CLOGIN_PASSWORD_FIELD.has_default_value = false
SA.CLOGIN_PASSWORD_FIELD.default_value = ""
SA.CLOGIN_PASSWORD_FIELD.type = 9
SA.CLOGIN_PASSWORD_FIELD.cpp_type = 9

SA.CLOGIN.name = "CLogin"
SA.CLOGIN.full_name = ".org.jiira.protobuf.CLogin"
SA.CLOGIN.nested_types = {}
SA.CLOGIN.enum_types = {}
SA.CLOGIN.fields = {SA.CLOGIN_USERNAME_FIELD, SA.CLOGIN_PASSWORD_FIELD}
SA.CLOGIN.is_extendable = false
SA.CLOGIN.extensions = {}
SA.SUSERDATA_CODE_FIELD.name = "code"
SA.SUSERDATA_CODE_FIELD.full_name = ".org.jiira.protobuf.SUserData.code"
SA.SUSERDATA_CODE_FIELD.number = 1
SA.SUSERDATA_CODE_FIELD.index = 0
SA.SUSERDATA_CODE_FIELD.label = 2
SA.SUSERDATA_CODE_FIELD.has_default_value = false
SA.SUSERDATA_CODE_FIELD.default_value = 0
SA.SUSERDATA_CODE_FIELD.type = 5
SA.SUSERDATA_CODE_FIELD.cpp_type = 1

SA.SUSERDATA.name = "SUserData"
SA.SUSERDATA.full_name = ".org.jiira.protobuf.SUserData"
SA.SUSERDATA.nested_types = {}
SA.SUSERDATA.enum_types = {}
SA.SUSERDATA.fields = {SA.SUSERDATA_CODE_FIELD}
SA.SUSERDATA.is_extendable = false
SA.SUSERDATA.extensions = {}
SA.SERROR_CODE_FIELD.name = "code"
SA.SERROR_CODE_FIELD.full_name = ".org.jiira.protobuf.SError.code"
SA.SERROR_CODE_FIELD.number = 1
SA.SERROR_CODE_FIELD.index = 0
SA.SERROR_CODE_FIELD.label = 2
SA.SERROR_CODE_FIELD.has_default_value = false
SA.SERROR_CODE_FIELD.default_value = 0
SA.SERROR_CODE_FIELD.type = 5
SA.SERROR_CODE_FIELD.cpp_type = 1

SA.SERROR.name = "SError"
SA.SERROR.full_name = ".org.jiira.protobuf.SError"
SA.SERROR.nested_types = {}
SA.SERROR.enum_types = {}
SA.SERROR.fields = {SA.SERROR_CODE_FIELD}
SA.SERROR.is_extendable = false
SA.SERROR.extensions = {}
SA.SSINGLEUPDATE_USERID_FIELD.name = "userID"
SA.SSINGLEUPDATE_USERID_FIELD.full_name = ".org.jiira.protobuf.SSingleUpdate.userID"
SA.SSINGLEUPDATE_USERID_FIELD.number = 1
SA.SSINGLEUPDATE_USERID_FIELD.index = 0
SA.SSINGLEUPDATE_USERID_FIELD.label = 2
SA.SSINGLEUPDATE_USERID_FIELD.has_default_value = false
SA.SSINGLEUPDATE_USERID_FIELD.default_value = 0
SA.SSINGLEUPDATE_USERID_FIELD.type = 5
SA.SSINGLEUPDATE_USERID_FIELD.cpp_type = 1

SA.SSINGLEUPDATE_KEYS_FIELD.name = "keys"
SA.SSINGLEUPDATE_KEYS_FIELD.full_name = ".org.jiira.protobuf.SSingleUpdate.keys"
SA.SSINGLEUPDATE_KEYS_FIELD.number = 2
SA.SSINGLEUPDATE_KEYS_FIELD.index = 1
SA.SSINGLEUPDATE_KEYS_FIELD.label = 3
SA.SSINGLEUPDATE_KEYS_FIELD.has_default_value = false
SA.SSINGLEUPDATE_KEYS_FIELD.default_value = {}
SA.SSINGLEUPDATE_KEYS_FIELD.type = 5
SA.SSINGLEUPDATE_KEYS_FIELD.cpp_type = 1

SA.SSINGLEUPDATE_IDS_FIELD.name = "IDs"
SA.SSINGLEUPDATE_IDS_FIELD.full_name = ".org.jiira.protobuf.SSingleUpdate.IDs"
SA.SSINGLEUPDATE_IDS_FIELD.number = 3
SA.SSINGLEUPDATE_IDS_FIELD.index = 2
SA.SSINGLEUPDATE_IDS_FIELD.label = 3
SA.SSINGLEUPDATE_IDS_FIELD.has_default_value = false
SA.SSINGLEUPDATE_IDS_FIELD.default_value = {}
SA.SSINGLEUPDATE_IDS_FIELD.type = 5
SA.SSINGLEUPDATE_IDS_FIELD.cpp_type = 1

SA.SSINGLEUPDATE_COUNTS_FIELD.name = "counts"
SA.SSINGLEUPDATE_COUNTS_FIELD.full_name = ".org.jiira.protobuf.SSingleUpdate.counts"
SA.SSINGLEUPDATE_COUNTS_FIELD.number = 4
SA.SSINGLEUPDATE_COUNTS_FIELD.index = 3
SA.SSINGLEUPDATE_COUNTS_FIELD.label = 3
SA.SSINGLEUPDATE_COUNTS_FIELD.has_default_value = false
SA.SSINGLEUPDATE_COUNTS_FIELD.default_value = {}
SA.SSINGLEUPDATE_COUNTS_FIELD.type = 5
SA.SSINGLEUPDATE_COUNTS_FIELD.cpp_type = 1

SA.SSINGLEUPDATE.name = "SSingleUpdate"
SA.SSINGLEUPDATE.full_name = ".org.jiira.protobuf.SSingleUpdate"
SA.SSINGLEUPDATE.nested_types = {}
SA.SSINGLEUPDATE.enum_types = {}
SA.SSINGLEUPDATE.fields = {SA.SSINGLEUPDATE_USERID_FIELD, SA.SSINGLEUPDATE_KEYS_FIELD, SA.SSINGLEUPDATE_IDS_FIELD, SA.SSINGLEUPDATE_COUNTS_FIELD}
SA.SSINGLEUPDATE.is_extendable = false
SA.SSINGLEUPDATE.extensions = {}
SA.CTEST_ID_FIELD.name = "id"
SA.CTEST_ID_FIELD.full_name = ".org.jiira.protobuf.CTest.id"
SA.CTEST_ID_FIELD.number = 1
SA.CTEST_ID_FIELD.index = 0
SA.CTEST_ID_FIELD.label = 2
SA.CTEST_ID_FIELD.has_default_value = false
SA.CTEST_ID_FIELD.default_value = 0
SA.CTEST_ID_FIELD.type = 5
SA.CTEST_ID_FIELD.cpp_type = 1

SA.CTEST_MSG_FIELD.name = "msg"
SA.CTEST_MSG_FIELD.full_name = ".org.jiira.protobuf.CTest.msg"
SA.CTEST_MSG_FIELD.number = 2
SA.CTEST_MSG_FIELD.index = 1
SA.CTEST_MSG_FIELD.label = 2
SA.CTEST_MSG_FIELD.has_default_value = false
SA.CTEST_MSG_FIELD.default_value = ""
SA.CTEST_MSG_FIELD.type = 9
SA.CTEST_MSG_FIELD.cpp_type = 9

SA.CTEST.name = "CTest"
SA.CTEST.full_name = ".org.jiira.protobuf.CTest"
SA.CTEST.nested_types = {}
SA.CTEST.enum_types = {}
SA.CTEST.fields = {SA.CTEST_ID_FIELD, SA.CTEST_MSG_FIELD}
SA.CTEST.is_extendable = false
SA.CTEST.extensions = {}
SA.STEST_ID_FIELD.name = "id"
SA.STEST_ID_FIELD.full_name = ".org.jiira.protobuf.STest.id"
SA.STEST_ID_FIELD.number = 1
SA.STEST_ID_FIELD.index = 0
SA.STEST_ID_FIELD.label = 2
SA.STEST_ID_FIELD.has_default_value = false
SA.STEST_ID_FIELD.default_value = 0
SA.STEST_ID_FIELD.type = 5
SA.STEST_ID_FIELD.cpp_type = 1

SA.STEST_MSG_FIELD.name = "msg"
SA.STEST_MSG_FIELD.full_name = ".org.jiira.protobuf.STest.msg"
SA.STEST_MSG_FIELD.number = 2
SA.STEST_MSG_FIELD.index = 1
SA.STEST_MSG_FIELD.label = 2
SA.STEST_MSG_FIELD.has_default_value = false
SA.STEST_MSG_FIELD.default_value = ""
SA.STEST_MSG_FIELD.type = 9
SA.STEST_MSG_FIELD.cpp_type = 9

SA.STEST.name = "STest"
SA.STEST.full_name = ".org.jiira.protobuf.STest"
SA.STEST.nested_types = {}
SA.STEST.enum_types = {}
SA.STEST.fields = {SA.STEST_ID_FIELD, SA.STEST_MSG_FIELD}
SA.STEST.is_extendable = false
SA.STEST.extensions = {}
SA.CHEART_TIME_FIELD.name = "time"
SA.CHEART_TIME_FIELD.full_name = ".org.jiira.protobuf.CHeart.time"
SA.CHEART_TIME_FIELD.number = 1
SA.CHEART_TIME_FIELD.index = 0
SA.CHEART_TIME_FIELD.label = 2
SA.CHEART_TIME_FIELD.has_default_value = false
SA.CHEART_TIME_FIELD.default_value = 0
SA.CHEART_TIME_FIELD.type = 3
SA.CHEART_TIME_FIELD.cpp_type = 2

SA.CHEART.name = "CHeart"
SA.CHEART.full_name = ".org.jiira.protobuf.CHeart"
SA.CHEART.nested_types = {}
SA.CHEART.enum_types = {}
SA.CHEART.fields = {SA.CHEART_TIME_FIELD}
SA.CHEART.is_extendable = false
SA.CHEART.extensions = {}

CHeart = protobuf.Message(SA.CHEART)
CLogin = protobuf.Message(SA.CLOGIN)
CTest = protobuf.Message(SA.CTEST)
SError = protobuf.Message(SA.SERROR)
SSingleUpdate = protobuf.Message(SA.SSINGLEUPDATE)
STest = protobuf.Message(SA.STEST)
SUserData = protobuf.Message(SA.SUSERDATA)

